### ISSUE TITLE
Support request: conversion from one locale to another

### ISSUE THREAD

**Issue by aborruso** [hroptatyr/dateutils#44]
Dear all,
I need to convert a date from one locale expression to another.

Something like from `26 Marzo 2016` (in Italian) to `26 March 2016` (English).

Is it possible to do it with dateutils utilities?

Thank you

**Comment by hroptatyr** [comment]
hiya,
unfortunately this is beyond the scope of dateutils (yet), as we're trying to be completely locale agnostic (we don't even need a libc with locale support).  This will make your scripts run the same way, regardless what the user locale or timezone is set to.

The reason you can have english month and day names is because out of all the non-numeric dates the english variant is by far the most wide-spread one.

That said, I'm not fully against support for other languages, I'm just wondering how the interface should look like, it complicates things if multiple locales can be specified.

**Comment by aborruso** [comment]
Hi @hroptatyr,
first of all thank you.

I want to add the reason of my request. Often I extract data from webpages, RSS, JSON & XML files, from around the world, and especially from my country (Italy).

I use simple but great tools like [csvkit](https://csvkit.readthedocs.org/en/0.9.1/), [jq](https://stedolan.github.io/jq/), but also the irreplaceable awk, sed, cat, tr, etc.. I work especially in bash.

The data I collect often have a date field, and often its expressed in the locale of the original website. Then, before making any kind of processing related to date, I must "normalize" the date info, converting all or in english or in numbers. Without do it, my data are not usable.

In example in bash I create this array to know always in example the correspondence between "novembre" (november in italian) and its expression in number.

```bash
declare -A month
for m in {1..12}; do
  mmm=$(LC_TIME=it_IT.utf8 date -d "2000-$m-1" "+%B")
  month[$mmm]=$m
done
```

If 'locale' in dateutils became an optional input parameters (the output could be always english), it would be even more useful than it already is.

Best regards

**Comment by hroptatyr** [comment]
Hi @aborruso,
I agree with you, it could be a killer feature of dateutils.  I would take the easy way out though and only (re)use the system locales, i.e. on systems with no LC_TIME (e.g. AIX) the functionality would be missing.

Or (depending on the licence) I would be fine with including complete locale specs from a third-party libc and maintaining them inside dateutils.

**Comment by hroptatyr** [comment]
Just a round-up, Andrea: I'm still undecided what to do about the locales, take their compiled form from the system (`/usr/share/locale/`), or include the sources of the locales in the repository.  What do you think?

The first approach would allow you to compile your own custom locale and dateutils would happily work with that without any recompiles or the like.  The second approach guarantees uniformity, on any two systems the same command line would produce identical results.

I've sort of changed my mind and now favour the second approach but I'm up for discussions.

**Comment by aborruso** [comment]
Hi @hroptatyr,
first of all to thank to be here about this feature request.

I agree with you and I prefer the second approach too, for portability and uniformity.

I can not wait to try it  :)

**Comment by hroptatyr** [comment]
Hey Andrea,
I've just pushed my first draft of the whole input locale feature.

In all of the tools you can go `--from-locale it_IT` now and then use italian month or weekday names.
If you want to try without installing it, you should also set the LOCALE_FILE environment variable, e.g.

    $ LOCALE_FILE=./data/locale ./src/dconv --from-locale it_IT -i '%B %Y' 'maggio 2016'
    2016-05-00

where pwd is the actual source tree (and the lastest master has been built).  Once installed the tools should find the locale file themselves.

Because the migration was so easy, I'm also going to provide `--locale` to set the output locale, who knows when that will come in handy.

**Comment by aborruso** [comment]
Hi @hroptatyr I'm a disaster.

I have tried to install again, and after make I have:

```
tzmap.c: In function 'cmd_cc':
tzmap.c:664:17: warning: missing initializer for field 'off' of 'struct tzmap_s' [-Wmissing-field-initializers]
   static struct tzmap_s r = {TZM_MAGIC};
                 ^
In file included from tzmap.c:59:0:
tzmap.h:58:10: note: 'off' declared here
  znoff_t off;
          ^
  CCLD     tzmap
make[2]: Leaving directory `/home/vagrant/dateutils/lib'
make[1]: Leaving directory `/home/vagrant/dateutils/lib'
Making all in src
make[1]: Entering directory `/home/vagrant/dateutils/src'
  LEX      dexpr-scanner.c
  YACC     dexpr-parser.c
byacc: e - line 38 of "/home/vagrant/dateutils/src/dexpr-parser.y", syntax error
%defines
^
make[1]: *** [dexpr-parser.c] Error 1
make[1]: Leaving directory `/home/vagrant/dateutils/src'
make: *** [all-recursive] Error 1
```

**Comment by hroptatyr** [comment]
Hi Andrea,
you can always try the tarball from https://drone.io/github.com/hroptatyr/dateutils/files
The parser should be generated there already.  I use drone (Ubuntu) as reference build chain.

**Comment by hroptatyr** [comment]
The real reason for the failure seems to be that byacc instead of bison is chosen on your system.
I guess, in the end it's my fault for not making the grammar file portable.  Personally I prefer byacc instead of bison, too.  I will get around to it at some point.

Disregard my previous post, the tarball does not contain the generated grammar and scanner.  So my new advice (for now) is to install bison.

**Comment by aborruso** [comment]
Yeaaaaaa

It works

![image](https://cloud.githubusercontent.com/assets/30607/15172050/7e735cd2-1753-11e6-8b60-e3100c8d8ba3.png)

**Comment by hroptatyr** [comment]
Nice :)

I will polish the whole thing now and then roll a release.
